=== bluskript/unstyle/src/assets/schemas/out/palette.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "type": "object",
  "properties": {
    "$schema": {
      "type": "string",
      "format": "string"
    },
    "id": {
      "type": "string",
      "format": "string"
    },
    "name": {
      "type": "string",
      "format": "string"
    },
    "dark": {
      "type": "boolean",
      "format": "boolean"
    },
    "extends": {
      "type": "string",
      "format": "string"
    },
    "variables": {
      "type": "object",
      "properties": {
        "code": {
          "type": "object",
          "properties": {
            "comment": {
              "type": "string",
              "format": "string"
            },
            "constant": {
              "type": "string",
              "format": "string"
            },
            "constant.builtin": {
              "type": "string",
              "format": "string"
            },
            "constant.character": {
              "type": "string",
              "format": "string"
            },
            "constant.character.escape": {
              "type": "string",
              "format": "string"
            },
            "constant.numeric": {
              "type": "string",
              "format": "string"
            },
            "constant.other": {
              "type": "string",
              "format": "string"
            },
            "entity": {
              "type": "string",
              "format": "string"
            },
            "entity.name": {
              "type": "string",
              "format": "string"
            },
            "entity.name.class": {
              "type": "string",
              "format": "string"
            },
            "entity.name.function": {
              "type": "string",
              "format": "string"
            },
            "entity.name.method": {
              "type": "string",
              "format": "string"
            },
            "entity.name.section": {
              "type": "string",
              "format": "string"
            },
            "entity.name.tag": {
              "type": "string",
              "format": "string"
            },
            "entity.name.type": {
              "type": "string",
              "format": "string"
            },
            "entity.other.attribute-name": {
              "type": "string",
              "format": "string"
            },
            "entity.other.inherited-class": {
              "type": "string",
              "format": "string"
            },
            "invalid": {
              "type": "string",
              "format": "string"
            },
            "invalid.deprecated": {
              "type": "string",
              "format": "string"
            },
            "invalid.illegal": {
              "type": "string",
              "format": "string"
            },
            "keyword": {
              "type": "string",
              "format": "string"
            },
            "keyword.control": {
              "type": "string",
              "format": "string"
            },
            "keyword.control.import": {
              "type": "string",
              "format": "string"
            },
            "keyword.operator": {
              "type": "string",
              "format": "string"
            },
            "keyword.other": {
              "type": "string",
              "format": "string"
            },
            "markup": {
              "type": "string",
              "format": "string"
            },
            "markup.bold": {
              "type": "string",
              "format": "string"
            },
            "markup.changed": {
              "type": "string",
              "format": "string"
            },
            "markup.deleted": {
              "type": "string",
              "format": "string"
            },
            "markup.heading": {
              "type": "string",
              "format": "string"
            },
            "markup.inline.raw": {
              "type": "string",
              "format": "string"
            },
            "markup.inserted": {
              "type": "string",
              "format": "string"
            },
            "markup.italic": {
              "type": "string",
              "format": "string"
            },
            "markup.list": {
              "type": "string",
              "format": "string"
            },
            "markup.quote": {
              "type": "string",
              "format": "string"
            },
            "markup.raw": {
              "type": "string",
              "format": "string"
            },
            "markup.underline": {
              "type": "string",
              "format": "string"
            },
            "markup.underline.link": {
              "type": "string",
              "format": "string"
            },
            "meta": {
              "type": "string",
              "format": "string"
            },
            "meta.block": {
              "type": "string",
              "format": "string"
            },
            "meta.class": {
              "type": "string",
              "format": "string"
            },
            "meta.function": {
              "type": "string",
              "format": "string"
            },
            "meta.function-call": {
              "type": "string",
              "format": "string"
            },
            "meta.method-call": {
              "type": "string",
              "format": "string"
            },
            "meta.preprocessor": {
              "type": "string",
              "format": "string"
            },
            "meta.return-type": {
              "type": "string",
              "format": "string"
            },
            "meta.selector": {
              "type": "string",
              "format": "string"
            },
            "meta.tag": {
              "type": "string",
              "format": "string"
            },
            "meta.type.annotation": {
              "type": "string",
              "format": "string"
            },
            "punctuation.definition.comment": {
              "type": "string",
              "format": "string"
            },
            "punctuation.definition.string": {
              "type": "string",
              "format": "string"
            },
            "punctuation.definition.variable": {
              "type": "string",
              "format": "string"
            },
            "punctuation.section.embedded": {
              "type": "string",
              "format": "string"
            },
            "storage": {
              "type": "string",
              "format": "string"
            },
            "storage.modifier": {
              "type": "string",
              "format": "string"
            },
            "storage.type": {
              "type": "string",
              "format": "string"
            },
            "string": {
              "type": "string",
              "format": "string"
            },
            "string.interpolated": {
              "type": "string",
              "format": "string"
            },
            "string.other": {
              "type": "string",
              "format": "string"
            },
            "string.quoted": {
              "type": "string",
              "format": "string"
            },
            "string.regexp": {
              "type": "string",
              "format": "string"
            },
            "support": {
              "type": "string",
              "format": "string"
            },
            "support.class": {
              "type": "string",
              "format": "string"
            },
            "support.constant": {
              "type": "string",
              "format": "string"
            },
            "support.function": {
              "type": "string",
              "format": "string"
            },
            "support.other": {
              "type": "string",
              "format": "string"
            },
            "support.type": {
              "type": "string",
              "format": "string"
            },
            "support.variable": {
              "type": "string",
              "format": "string"
            },
            "variable": {
              "type": "string",
              "format": "string"
            },
            "variable.function": {
              "type": "string",
              "format": "string"
            },
            "variable.language": {
              "type": "string",
              "format": "string"
            },
            "variable.name": {
              "type": "string",
              "format": "string"
            },
            "variable.other": {
              "type": "string",
              "format": "string"
            },
            "variable.parameter": {
              "type": "string",
              "format": "string"
            }
          },
          "additionalProperties": false
        },
        "ui": {
          "type": "object",
          "properties": {
            "background": {
              "type": "string",
              "format": "string"
            },
            "background-dark": {
              "type": "string",
              "format": "string"
            },
            "background-light": {
              "type": "string",
              "format": "string"
            },
            "background-lighter": {
              "type": "string",
              "format": "string"
            },
            "primary": {
              "type": "string",
              "format": "string"
            },
            "primary-light": {
              "type": "string",
              "format": "string"
            },
            "primary-dark": {
              "type": "string",
              "format": "string"
            },
            "secondary": {
              "type": "string",
              "format": "string"
            },
            "secondary-light": {
              "type": "string",
              "format": "string"
            },
            "secondary-dark": {
              "type": "string",
              "format": "string"
            },
            "text": {
              "type": "string",
              "format": "string"
            },
            "text-dark": {
              "type": "string",
              "format": "string"
            },
            "text-darker": {
              "type": "string",
              "format": "string"
            },
            "text-contrast": {
              "type": "string",
              "format": "string"
            },
            "selection": {
              "type": "string",
              "format": "string"
            },
            "border": {
              "type": "string",
              "format": "string"
            },
            "border-light": {
              "type": "string",
              "format": "string"
            },
            "border-dark": {
              "type": "string",
              "format": "string"
            },
            "link": {
              "type": "string",
              "format": "string"
            },
            "link-visited": {
              "type": "string",
              "format": "string"
            },
            "link-hover": {
              "type": "string",
              "format": "string"
            },
            "button-background": {
              "type": "string",
              "format": "string"
            },
            "button-background-hover": {
              "type": "string",
              "format": "string"
            },
            "button-text": {
              "type": "string",
              "format": "string"
            },
            "button-border": {
              "type": "string",
              "format": "string"
            }
          },
          "additionalProperties": false
        }
      },
      "additionalProperties": false
    }
  },
  "required": [
    "id",
    "name",
    "dark",
    "variables"
  ],
  "additionalProperties": false
}

=== bluskript/unstyle/src/assets/themes/rose_pine.json
{
	"$schema": "../schemas/out/palette.json",
	"id": "rose-pine",
	"name": "Rose Pine",
	"dark": true,
	"variables": {
		"ui": {
			"background-dark": "#191724",
			"background": "#1f1d2e",
			"background-light": "#21202e",
			"background-lighter": "#26233a",
			"border": "#6e6a86",
			"selection": "#908caa",
			"text": "#e0def4",
			"text-dark": "#908caa",
			"text-darker": "#6e6a86",
			"text-contrast": "#191724",
			"primary": "#eb6f92",
			"secondary": "#c4a7e7",
			"link": "#9ccfd8",
			"link-visited": "#c4a7e7",
			"button-border": "#000000"
		},
		"code": {
			"comment": "#1f1e33"
		}
	}
}

=== bluskript/unstyle/src/assets/themes/bocchi.json
{
	"$schema": "../schemas/out/palette.json",
	"id": "bocchi",
	"name": "Bocchi",
	"dark": false,
	"variables": {
		"ui": {
			"background-dark": "#ece3ff",
			"background": "#e4d8ff",
			"background-light": "#d0c5e9",
			"border": "#78699a",
			"selection": "#7c42ff",
			"text": "#140f1f",
			"text-dark": "#4d445f",
			"text-darker": "#978db0",
			"text-contrast": "#140f1f",
			"primary": "#3d9cff",
			"secondary": "#ffbb24",
			"link": "#3c3545",
			"link-visited": "#58325c",
			"button-border": "#000000"
		}
	}
}
