=== bluskript/unstyle/src/assets/schemas/base/stylesheet-base.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "type": "object",
  "properties": {
    "$schema": {
      "type": "string",
      "format": "string"
    },
    "id": {
      "type": "string",
      "format": "string"
    },
    "name": {
      "type": "string",
      "format": "string"
    },
    "glob": {
      "type": "string",
      "format": "string"
    },
    "description": {
      "type": "string",
      "format": "string"
    },
    "author": {
      "type": "string",
      "format": "string"
    },
    "variables": {
      "type": "object"
    }
  },
  "required": [
    "id",
    "name",
    "glob",
    "variables"
  ],
  "additionalProperties": false
}

=== bluskript/unstyle/src/assets/websites/hackernews.json
{
  "$schema": "../schemas/out/stylesheet.json",
  "id": "hackernews",
  "name": "Hackernews",
  "glob": "news.ycombinator.com",
  "description": "Custom theme for HackerNews",
  "author": "Blusk",
  "variables": {
    "background": ["ui:background-dark"],
    "body-background": ["ui:background"],
    "lighter-background": ["ui:background-lighter"],
    "text": ["ui:text"],
    "text-post-text": ["ui:text-dark"],
    "comment-text": ["ui:text"],
    "comment-head-text": ["ui:text-dark"],
    "comment-box-background": ["ui:background-light"],
    "comment-box-text": ["ui:text-dark"],
    "poll-question-text": ["ui:text"],
    "yclinks-text": ["ui:text"],
    "comment-box-border": ["ui:border"],
    "story-points-text": ["ui:text-dark"],
    "story-ranking-text": ["ui:text-dark"],
    "selection": ["ui:selection"],
    "border": ["ui:border"],
    "link": ["ui:link"],
    "link-visited": ["ui:link-visited"],
    "header-text": ["ui:text-contrast"],
    "logo-border": ["ui:border-dark"],
    "yellow-td-background": ["ui:primary-light"],
    "unknown-green-thing": ["ui:secondary-light"]
  }
}
